version: '3'

services:
  web:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: mysql+mysqlconnector://root:Assetmanagement@db/assetsmanagement

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: assetsmanagement
      MYSQL_USER: root
      MYSQL_PASSWORD: Assetmanagement
      MYSQL_ROOT_PASSWORD: Assetmanagement
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
